---
- hosts: localhost
  vars_files:
    - ["settings.yml", "defaults/settings.yml.default"]
  roles:
    - { role: docker, tags: ["core", "docker"] }
    - { role: cloudflare, tags: ["core", "cloudflare"] }
    - { role: traefik, tags: ["core", "traefik"] }
    - { role: portainer, tags: ["core", "portainer"] }
    - { role: filebrowser, tags: ["filebrowser"] }
    - { role: rutorrent, tags: ["rutorrent"] }
    - { role: nzbget, tags: ["nzbget"] }