---
- hosts: localhost
  become: true
  vars_files: ["defaults/settings.yml.default", "settings.yml"]
  roles:
    # Minimal Stack
    - { role: docker, tags: ["core", "docker"] }
    - { role: cloudflare, tags: ["core", "cloudflare"] }
    - { role: traefik, tags: ["core", "traefik"] }
    - { role: portainer, tags: ["core", "portainer"] }
    - { role: gotify, tags: ["core", "gotify"] }
    - { role: filetree, tags: ["core", "filetree"] }
    - { role: hardening, tags: ["core", "hardening"] }
    - { role: homer, tags: ["core", "homer"] }
    - { role: watchtower, tags: ["core", "watchtower"] }
    - { role: postfix, tags: ["core", "watchtower", "postfix"] }

    # Download
    - { role: flood, tags: ["download", "torrent", "flood"] }
    - { role: qbittorrent, tags: ["download", "torrent", "qbittorrent"] }
    - { role: rutorrent, tags: ["rutorrent"] }
    - { role: nzbget, tags: ["usenet", "nzbget"] }
    - { role: sabnzbd, tags: ["sabnzbd"] }

    # Media
    - { role: jellyfin, tags: ["jellyfin"] }
    - { role: navidrome, tags: ["navidrome"] }
    - { role: kavita, tags: ["kavita"] }

    # PVR
    - { role: prowlarr, tags: ["pvr", "usenet", "prowlarr"] }
    - { role: sonarr, tags: ["pvr", "usenet", "sonarr"] }
    - { role: radarr, tags: ["pvr", "usenet", "radarr"] }
    - { role: lidarr, tags: ["pvr", "usenet", "lidarr"] }
    - { role: readarr, tags: ["pvr", "usenet", "readarr"] }
    - { role: bazarr, tags: ["pvr", "bazarr"] }
    #- { role: traktarr, tags: [usenet, "rr", "traktarr"] }
    - { role: jackett, tags: ["pvr", "torrent", "jackett"] }

    # Tools
    - { role: filebrowser, tags: ["tools", "filebrowser"] }
    - { role: syncthing, tags: ["tools", "syncthing"] }
    - { role: archivebox, tags: ["tools", "archivebox"] }
    - { role: whoami, tags: ["whoami"] }

    # Monitoring
    - { role: netdata, tags: ["monitoring", "netdata"] }
    - { role: speedtesttracker, tags: ["speedtesttracker"] }
    - { role: librespeed, tags: ["monitoring", "librespeed"] }
    - { role: scrutiny, tags: ["monitoring", "scrutiny"] }