---
- name: SEEDbox
  hosts: localhost
  vars_files: ["defaults/settings.yml.default", "settings.yml"]
  roles:
    # Minimal Stack
    - { role: docker, tags: ["core", "docker"] }
    - { role: cloudflare, tags: ["core", "cloudflare"] }
    - { role: traefik, tags: ["core", "traefik"] }
    - { role: crowdsec, tags: ["core", "crowdsec"] }
    - { role: portainer, tags: ["core", "portainer"] }
    - { role: authelia, tags: ["core", "authelia"] }
    - { role: filetree, tags: ["core", "filetree"] }
    - { role: hardening, tags: ["core", "hardening"] }
    - { role: homer, tags: ["core", "homer"] }
    - { role: watchtower, tags: ["core", "watchtower"] }
    - { role: postfix, tags: ["core", "watchtower", "postfix"] }

    # Download
    - { role: qbittorrent, tags: ["download", "torrent", "qbittorrent"] }
    - { role: rutorrent, tags: ["download", "torrent", "rutorrent"] }
    - { role: nzbget, tags: ["download", "usenet", "nzbget"] }
    - { role: sabnzbd, tags: ["download", "usenet", "sabnzbd"] }
    - { role: flood, tags: ["download", "torrent", "flood"] }
    - { role: qui, tags: ["download", "torrent", "qui"] }

    # Media
    - { role: seerr, tags: ["media", "seerr"] }
    - { role: jellyfin, tags: ["media", "jellyfin"] }
    - { role: navidrome, tags: ["media", "navidrome"] }
    - { role: kavita, tags: ["media", "kavita"] }
    - { role: yamtrack, tags: ["media", "yamtrack"] }

    # PVR
    - { role: prowlarr, tags: ["pvr", "usenet", "torrent", "prowlarr"] }
    - { role: sonarr, tags: ["pvr", "usenet", "torrent", "sonarr"] }
    - { role: radarr, tags: ["pvr", "usenet", "torrent", "radarr"] }
    - { role: lidarr, tags: ["pvr", "usenet", "torrent", "lidarr"] }
    - { role: readarr, tags: ["pvr", "usenet", "torrent", "readarr"] }
    - { role: bazarr, tags: ["pvr", "bazarr"] }

    # Tools
    - { role: filebrowser, tags: ["tools", "filebrowser"] }
    - { role: syncthing, tags: ["tools", "syncthing"] }
    - { role: archivebox, tags: ["tools", "archivebox"] }
    - { role: whoami, tags: ["tools", "whoami"] }

    # Monitoring
    - { role: netdata, tags: ["monitoring", "netdata"] }
    - { role: speedtesttracker, tags: ["monitoring", "speedtesttracker"] }
    - { role: librespeed, tags: ["monitoring", "librespeed"] }
    - { role: scrutiny, tags: ["monitoring", "scrutiny"] }

    # Extras
    - { role: tinymotd, tags: ["extras", "tinymotd"] }
