---
- hosts: localhost
  vars_files: ["defaults/settings.yml.default", "settings.yml"]
  roles:
    # Minimal Stack
    - { role: docker, tags: ["core", "docker"] }
    - { role: cloudflare, tags: ["core", "cloudflare"] }
    - { role: traefik, tags: ["core", "traefik"] }
    - { role: portainer, tags: ["core", "portainer"] }
    - { role: authelia, tags: ["core", "authelia"] }
    - { role: filetree, tags: ["core", "filetree"] }
    - { role: hardening, tags: ["core", "hardening"] }

    - { role: homer, tags: ["homer"] }
    # Download
    - { role: flood, tags: ["torrent", "flood"] }
    - { role: qbittorrent, tags: ["torrent", "qbittorrent"] }
    - { role: rutorrent, tags: ["rutorrent"] }
    - { role: nzbget, tags: ["usenet", "nzbget"] }
    - { role: sabnzbd, tags: ["sabnzbd"] }
    # Media
    - { role: jellyfin, tags: ["jellyfin"] }
    - { role: navidrome, tags: ["navidrome"] }
    - { role: kavita, tags: ["kavita"] }
    # Monitoring
    - { role: scrutiny, tags: ["monitoring", "scrutiny"] }
    - { role: netdata, tags: ["monitoring", "netdata"] }
    - { role: watchtower, tags: ["monitoring", "watchtower"] }
    - { role: postfix, tags: ["monitoring", "watchtower", "postfix"] }
    # Tools
    - { role: filebrowser, tags: ["filebrowser"] }

    - { role: whoami, tags: ["tools", "whoami"] }
    - { role: librespeed, tags: ["tools", "librespeed"] }
    - { role: archivebox, tags: ["tools", "archivebox"] }
    #- { role: speedtesttracker, tags: ["tools", "speedtesttracker"] }
    # *arr Apps
    - { role: prowlarr, tags: ["usenet", "rr", "prowlarr"] }
    - { role: sonarr, tags: ["usenet", "rr", "sonarr"] }
    - { role: radarr, tags: ["usenet", "rr", "radarr"] }
    - { role: lidarr, tags: ["usenet", "rr", "lidarr"] }
    - { role: readarr, tags: ["usenet", "rr", "readarr"] }
    - { role: bazarr, tags: ["usenet", "rr", "bazarr"] }
    #- { role: traktarr, tags: [usenet, "rr", "traktarr"] }
