---
- hosts: localhost
  vars_files:
    - ["settings.yml", "defaults/settings.yml.default"]
  roles:
    - { role: docker, tags: ["core", "docker"] }
    - { role: cloudflare, tags: ["core", "cloudflare"] }
    - { role: traefik, tags: ["core", "traefik"] }
    - { role: portainer, tags: ["core", "portainer"] }
    - { role: filebrowser, tags: ["filebrowser"] }
    - { role: rutorrent, tags: ["rutorrent"] }
    - { role: nzbget, tags: ["nzbget"] }
    - { role: homer, tags: ["homer"] }
    - { role: scrutiny, tags: ["monitoring", "scrutiny"] }
    - { role: jellyfin, tags: ["jellyfin"] }
    - { role: netdata, tags: ["monitoring", "netdata"] }
    - { role: hardening, tags: ["hardening"] }
    - { role: navidrome, tags: ["navidrome"] }
    - { role: watchtower, tags: ["monitoring", "watchtower"] }
    - { role: postfix, tags: ["monitoring", "postfix"] }
    - { role: prowlarr, tags: ["rr", "prowlarr"] }
    - { role: authelia, tags: ["authelia"] }