---
- name: Stop and remove any existing container
  docker_container:
    name: watchtower
    state: absent

- name: Create and start container
  docker_container:
    name: watchtower
    image: "containrrr/watchtower:{{ watchtower.tag }}"
    pull: yes
    recreate: true
    networks:
      - name: gotify
        aliases:
          - watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart_policy: unless-stopped
    state: started
    env:
      TZ: "{{ tz }}"
      WATCHTOWER_MONITOR_ONLY: "{{ watchtower.monitor_only }}"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      # Update containers every day at 5:00 a.m.
      WATCHTOWER_SCHEDULE: "0 0 5 * * *"
      WATCHTOWER_NOTIFICATIONS: gotify
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: http://gotify:80
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "{{ watchtower.notification_gotify_token }}"