- name: Settings | Wait for 'config.yml' to be created
  wait_for:
    path: "{{ homer.folder }}/config.yml"
    state: present

- name: Settings | Wait for 10 seconds before stopping homer container
  wait_for:
    timeout: 10

- name: Settings | Stop container
  docker_container:
    name: homer
    state: stopped

- name: Settings | GIT Clone/Pull Icons Repository
  git:
    repo: https://github.com/WalkxCode/dashboard-icons.git
    dest: "{{ homer.folder }}/homer-icons"
    update: yes
    force: yes

- name: Settings | Import custom 'base.yml'
  template:
    src: config.yml.j2
    dest: "{{ homer.folder }}/discovery/base.yml"
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Settings | Start container
  docker_container:
    name: homer
    state: started