- name: Settings | Wait for 'config.yml' to be created
  ansible.builtin.wait_for:
    path: "{{ homer.folder }}/config.yml"
    state: present

- name: Settings | Wait for 10 seconds before stopping homer container
  ansible.builtin.wait_for:
    timeout: 10

- name: Settings | Stop container
  community.docker.docker_container:
    name: homer
    state: stopped

- name: Settings | GIT Clone/Pull Icons Repository
  ansible.builtin.git:
    repo: https://github.com/homarr-labs/dashboard-icons.git
    version: main
    dest: "{{ homer.folder }}/homer-icons"
    update: true
    force: true

- name: Settings | Import custom 'base.yml'
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ homer.folder }}/discovery/base.yml"
    force: true
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0775"

- name: Settings | Start container
  community.docker.docker_container:
    name: homer
    state: started
