---
- name: Create directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ group }} recurse=yes"
  with_items:
    - "{{ netdata.folder }}"
    - "{{ netdata.folder }}/config"
    - "{{ netdata.folder }}/lib"
    - "{{ netdata.folder }}/cache"

- name: Create and start container
  docker_container:
    name: netdata
    hostname: "{{ netdata.subdomain }}.{{ domain }}"
    image: "netdata/netdata"
    pull: yes
    recreate: true
    volumes:
      - "{{ netdata.folder }}/config:/etc/netdata"
      - "{{ netdata.folder }}/lib:/var/lib/netdata"
      - "{{ netdata.folder }}/cache:/var/cache/netdata"
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - name: web
        aliases:
          - netdata
    restart_policy: unless-stopped
    state: started
    capabilities:
      - SYS_PTRACE
    security_opts:
      - apparmor:unconfined
    labels:
      # Trafik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.netdata.rule: "Host(`{{ netdata.subdomain }}.{{ domain }}`)"
      traefik.http.routers.netdata.entrypoints: "websecure"
      traefik.http.services.netdata.loadbalancer.server.port: "19999"
      traefik.http.routers.netdata.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "Netdata"
      homer.service: "Monitoring"
      homer.priority: "1"
      homer.subtitle: "Monitor everything in real time"
      homer.url: "https://{{ netdata.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/png/netdata.png"
      homer.target: "_blank"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"
      DO_NOT_TRACK: 1
      CONTAINERS: 1