- name: Settings | Clear 'ControlUsername'
  lineinfile:
    path: "{{ nzbget.folder }}/nzbget.conf"
    regexp: '^ControlUsername\s*=.*'
    line: 'ControlUsername='
    state: present

- name: Settings | Clear 'ControlPassword'
  lineinfile:
    path: "{{ nzbget.folder }}/nzbget.conf"
    regexp: '^ControlPassword\s*=.*'
    line: 'ControlPassword='
    state: present

- name: Settings | Set 'RestrictedUsername'
  lineinfile:
    path: "{{ nzbget.folder }}/nzbget.conf"
    regexp: '^RestrictedUsername\s*=.*'
    line: 'RestrictedUsername={{ nzbget.restricted_username }}'
    state: present

- name: Settings | Set 'RestrictedPassword'
  lineinfile:
    path: "{{ nzbget.folder }}/nzbget.conf"
    regexp: '^RestrictedPassword\s*=.*'
    line: 'RestrictedPassword={{ nzbget.restricted_password }}'
    state: present