---
- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    force_apt_get: true
    update_cache: true

- name: Install Fail2Ban
  ansible.builtin.include_tasks: "fail2ban/main.yml"
  when: not use_crowdsec | bool

- name: Install Unattended Upgrades
  ansible.builtin.include_tasks: "unattendedupgrades/main.yml"
