---
- name: Create directories
  file:
    path: "{{ lidarr.folder }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Create and start container
  docker_container:
    name: lidarr
    image: "ghcr.io/linuxserver/lidarr"
    pull: yes
    recreate: true
    volumes:
      - "{{ lidarr.folder }}:/config"
      - "{{ data_folder }}:/data"
    networks:
      - name: web
        aliases:
          - lidarr
    restart_policy: unless-stopped
    state: started
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.lidarr.rule: "Host(`{{ lidarr.subdomain }}.{{ domain }}`)"
      traefik.http.routers.lidarr.entrypoints: "websecure"
      traefik.http.services.lidarr.loadbalancer.server.port: "8686"
      traefik.http.routers.lidarr.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "Lidarr"
      homer.service: "PVR"
      homer.priority: "3"
      homer.subtitle: "Music collection manager for Usenet and BitTorrent users"
      homer.url: "https://{{ lidarr.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/png/lidarr.png"
      homer.target: "_blank"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"

- name: Wait for 'config.xml' to be created
  wait_for:
    path: "{{ lidarr.folder }}/config.xml"
    state: present

- name: Wait for 10 seconds
  wait_for:
    timeout: 10

- name: Settings Tasks
  include_tasks: "settings/main.yml"