---
- name: Stop and remove any existing container
  docker_container:
    name: navidrome
    state: absent

- name: Create directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ group }} recurse=yes"
  with_items:
    - "{{ navidrome.folder }}"
    - "{{ navidrome.folder }}/data"
    - "{{ data_folder }}/media/music"

- name: Create and start container
  docker_container:
    name: navidrome
    image: "deluan/navidrome:latest"
    pull: yes
    recreate: true
    volumes:
      - "{{ navidrome.folder }}/data:/data"
      - "{{ data_folder }}/media/music:/music:ro"
    user: "{{ uid }}:{{ gid }}"
    networks:
      - name: web
        aliases:
          - navidrome
    restart_policy: unless-stopped
    state: started
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.navidrome.rule: "Host(`{{ navidrome.subdomain }}.{{ domain }}`)"
      traefik.http.routers.navidrome.entrypoints: "websecure"
      traefik.http.services.navidrome.loadbalancer.server.port: "4533"
      # Homer
      homer.enable: "true"
      homer.name: "Navidrome"
      homer.service: "Media"
      homer.priority: "200"
      homer.subtitle: "Enjoy your music collection from anywhere"
      homer.url: "https://{{ navidrome.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/png/navidrome.png"
      homer.target: "_blank"
    env:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""