---
- name: Create main directory hierarchy
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ group }} recurse=yes"
  with_items:
    - "{{ data_folder }}/torrents"
    - "{{ data_folder }}/torrents/books"
    - "{{ data_folder }}/torrents/misc"
    - "{{ data_folder }}/torrents/movies"
    - "{{ data_folder }}/torrents/music"
    - "{{ data_folder }}/torrents/software"
    - "{{ data_folder }}/torrents/tv"

    - "{{ data_folder }}/usenet"
    - "{{ data_folder }}/usenet/books"
    - "{{ data_folder }}/usenet/misc"
    - "{{ data_folder }}/usenet/movies"
    - "{{ data_folder }}/usenet/music"
    - "{{ data_folder }}/usenet/software"
    - "{{ data_folder }}/usenet/tv"

    - "{{ data_folder }}/media"
    - "{{ data_folder }}/media/books"
    - "{{ data_folder }}/media/misc"
    - "{{ data_folder }}/media/movies"
    - "{{ data_folder }}/media/music"
    - "{{ data_folder }}/media/software"
    - "{{ data_folder }}/media/tv"
