---
- name: Install Fail2Ban package
  ansible.builtin.package:
    name:
      - fail2ban
    state: present
    install_recommends: true

- name: Copy Fail2Ban configuration
  ansible.builtin.template:
    src: jail.conf.j2
    dest: "/etc/fail2ban/jail.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0775"
    force: true
  notify: Restart Fail2Ban service
