---
- name: Stop and remove any existing container
  docker_container:
    name: filebrowser
    state: absent

- name: Create directories
  file:
    path: "{{ filebrowser.folder }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: "Check if filebrowser config file exists"
  stat:
    path: "{{ filebrowser.folder }}/filebrowser.json"
  register: filebrowser_config

- name: "Check if filebrowser database file exists"
  stat:
    path: "{{ filebrowser.folder }}/filebrowser.db"
  register: filebrowser_database

- name: "Create filebrowser config file"
  template:
    src: filebrowser.json.j2
    dest: "{{ filebrowser.folder }}/filebrowser.json"
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
  when: not filebrowser_config.stat.exists

- name: "Create filebrowser database file"
  template:
    src: filebrowser.db
    dest: "{{ filebrowser.folder }}/filebrowser.db"
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
  when: not filebrowser_database.stat.exists

- name: Create and start container
  docker_container:
    name: filebrowser
    image: "filebrowser/filebrowser:{{ filebrowser.tag }}"
    pull: yes
    recreate: true
    volumes:
      - "{{ data_folder }}:/srv"
      - "{{ filebrowser.folder }}/filebrowser.db:/database.db"
      - "{{ filebrowser.folder }}/filebrowser.json:/.filebrowser.json"
    user: "{{ uid }}:{{ gid }}"
    networks:
      - name: web
        aliases:
          - filebrowser
    restart_policy: unless-stopped
    state: started
    labels:
      # Treafik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.filebrowser.rule: "Host(`{{ filebrowser.subdomain }}.{{ domain }}`)"
      traefik.http.routers.filebrowser.entrypoints: "websecure"
      traefik.http.services.filebrowser.loadbalancer.server.port: "80"
      # Homer
      homer.enable: "true"
      homer.name: "Filebrowser"
      homer.service: "Tools"
      homer.priority: "500"
      homer.subtitle: "File managing interface"
      homer.url: "https://{{ filebrowser.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/svg/filebrowser.svg"
      homer.target: "_blank"
    env:
      TZ: "{{ tz }}"
