---
- name: Create directories
  file:
    path: "{{ scrutiny.folder }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Get disks
  shell: for line in $(lsblk --noheadings --list --scsi --output name); do echo "/dev/${line}:/dev/${line}"; done
  register: lsblk_disks
  changed_when: false

- name: Create and start container
  docker_container:
    name: scrutiny
    image: "ghcr.io/linuxserver/scrutiny"
    pull: yes
    recreate: true
    volumes:
      - "{{ scrutiny.folder }}:/config"
      - "/run/udev:/run/udev:ro"
    devices: "{{ lsblk_disks.stdout_lines }}"
    networks:
      - name: web
        aliases:
          - scrutiny
    restart_policy: unless-stopped
    state: started
    capabilities:
      - SYS_RAWIO
      - SYS_ADMIN
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.scrutiny.rule: "Host(`{{ scrutiny.subdomain }}.{{ domain }}`)"
      traefik.http.routers.scrutiny.entrypoints: "websecure"
      traefik.http.services.scrutiny.loadbalancer.server.port: "8080"
      traefik.http.routers.scrutiny.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "Scrutiny"
      homer.service: "Monitoring"
      homer.priority: "2"
      homer.subtitle: "Hard Drive S.M.A.R.T Monitoring"
      homer.url: "https://{{ scrutiny.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/png/scrutiny.png"
      homer.target: "_blank"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"
      SCRUTINY_API_ENDPOINT: http://localhost:8080
      SCRUTINY_WEB: true | bool
      SCRUTINY_COLLECTOR: true | bool