---
- name: Create and start Cloudflare Dynamic DNS Updater
  community.docker.docker_container:
    name: cf-ddns
    image: "favonia/cloudflare-ddns:{{ cloudflare.tag_ddns }}"
    pull: true
    recreate: true
    state: started
    restart_policy: always
    env:
      CLOUDFLARE_API_TOKEN: "{{ cloudflare.api_key }}"
      DOMAINS: "{{ domain }}"
      PROXIED: "true"
      RRTYPE: "A"
