---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0775"
    recurse: true
  loop:
    - "{{ qbittorrent.folder }}"

- name: Create and start container
  community.docker.docker_container:
    name: qbittorrent
    image: "ghcr.io/linuxserver/qbittorrent:{{ qbittorrent.tag }}"
    pull: true
    recreate: true
    volumes:
      - "{{ qbittorrent.folder }}:/config"
      - "{{ data_folder }}/torrents:/downloads"
    networks:
      - name: web
        aliases:
          - qbittorrent
    restart_policy: unless-stopped
    state: started
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent.subdomain }}.{{ domain }}`)"
      traefik.http.routers.qbittorrent.entrypoints: "websecure"
      traefik.http.services.qbittorrent.loadbalancer.server.port: "8080"
      # traefik.http.middlewares.referer.headers.customresponseheaders.Referer: "{{ qbittorrent.subdomain }}.{{ domain }}"
      traefik.http.routers.qbittorrent.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "qBittorrent"
      homer.service: "Download"
      homer.priority: "400"
      homer.subtitle: "BitTorrent client based on Qt and libtorrent"
      homer.url: "https://{{ qbittorrent.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/svg/qbittorrent.svg"
      homer.target: "_blank"
    published_ports:
      - "51413:51413"
      - "{{ qbittorrent.bittorrent_port }}:{{ qbittorrent.bittorrent_port }}"
      - "{{ qbittorrent.bittorrent_port }}:{{ qbittorrent.bittorrent_port }}/udp"
    env:
      TZ: "{{ tz | string }}"
      PUID: "{{ uid | string }}"
      PGID: "{{ gid | string }}"
      WEBUI_PORT: "8080"

- name: Settings | Wait for 'qBittorrent.conf' to be created
  ansible.builtin.wait_for:
    path: "{{ qbittorrent.folder }}/qBittorrent/qBittorrent.conf"
    state: present

- name: Settings | Wait for 10 seconds before stopping qbittorrent container
  ansible.builtin.wait_for:
    timeout: 10

- name: Settings | Stop container
  community.docker.docker_container:
    name: qbittorrent
    state: stopped

- name: QBittorrent Main Settings Tasks
  ansible.builtin.include_tasks: "settings/main.yml"
- name: Re-Start qBittorrent container
  community.docker.docker_container:
    name: qbittorrent
    state: started
