---
- name: Create directories
  file:
    path: "{{ qbittorrent.folder }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Create and start container
  docker_container:
    name: qbittorrent
    image: "ghcr.io/linuxserver/qbittorrent:{{ qbittorrent.tag }}"
    pull: yes
    recreate: true
    volumes:
      - "{{ qbittorrent.folder }}:/config"
      - "{{ data_folder }}/torrents:/downloads"
    networks:
      - name: web
        aliases:
          - qbittorrent
    restart_policy: unless-stopped
    state: started
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent.subdomain }}.{{ domain }}`)"
      traefik.http.routers.qbittorrent.entrypoints: "websecure"
      traefik.http.services.qbittorrent.loadbalancer.server.port: "8080"
      #traefik.http.middlewares.referer.headers.customresponseheaders.Referer: "{{ qbittorrent.subdomain }}.{{ domain }}"
      traefik.http.routers.qbittorrent.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "qBittorrent"
      homer.service: "Download"
      homer.priority: "400"
      homer.subtitle: "Best BitTorrent client"
      homer.url: "https://{{ qbittorrent.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/png/qbittorrent.png"
      homer.target: "_blank"
    published_ports:
      - "51413:51413"
      - "6881:6881"
      - "6881:6881/udp"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"
      WEBUI_PORT: "8080"

- name: Settings | Wait for 'qBittorrent.conf' to be created
  wait_for:
    path: "{{ qbittorrent.folder }}/qBittorrent/qBittorrent.conf"
    state: present

- name: Settings | Wait for 10 seconds before stopping qbittorrent container
  wait_for:
    timeout: 10

- name: Settings | Stop container
  docker_container:
    name: qbittorrent
    state: stopped

- name: qBittorrent Main Settings Tasks
  include_tasks: "settings/main.yml"

- name: Re-Start qBittorrent container
  docker_container:
    name: qbittorrent
    state: started