---
- name: Create directories
  file:
    path: "{{ prowlarr.folder }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Create and start container
  docker_container:
    name: prowlarr
    image: "ghcr.io/linuxserver/prowlarr:develop"
    pull: yes
    recreate: true
    volumes:
      - "{{ prowlarr.folder }}:/config"
    networks:
      - name: web
        aliases:
          - prowlarr
    restart_policy: unless-stopped
    state: started
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.prowlarr.rule: "Host(`{{ prowlarr.subdomain }}.{{ domain }}`)"
      traefik.http.routers.prowlarr.entrypoints: "websecure"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
      traefik.http.routers.prowlarr.middlewares: "authelia@docker"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"