---
- name: Create directories
  file:
    path: "{{ prowlarr.folder }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Create and start container
  docker_container:
    name: prowlarr
    image: "ghcr.io/linuxserver/prowlarr:{{ prowlarr.tag }}"
    pull: yes
    recreate: true
    volumes:
      - "{{ prowlarr.folder }}:/config"
    networks:
      - name: web
        aliases:
          - prowlarr
    restart_policy: unless-stopped
    state: started
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.prowlarr.rule: "Host(`{{ prowlarr.subdomain }}.{{ domain }}`)"
      traefik.http.routers.prowlarr.entrypoints: "websecure"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
      traefik.http.routers.prowlarr.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "Prowlarr"
      homer.service: "Tools"
      homer.priority: "400"
      homer.subtitle: "Indexer manager/proxy"
      homer.url: "https://{{ prowlarr.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/svg/prowlarr.svg"
      homer.target: "_blank"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"