---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
    recurse: yes
  loop:
    - "{{ authelia.folder }}"
    - "{{ authelia.redis.folder }}"

- name: "Create authelia users database file"
  template:
    src: users_database.yml.j2
    dest: "{{ authelia.folder }}/users_database.yml"
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775


- name: "Create authelia config file"
  template:
    src: configuration.yml.j2
    dest: "{{ authelia.folder }}/configuration.yml"
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Create the authelia network
  docker_network:
    name: authelia

- name: Create and start authelia redis container
  docker_container:
    name: authelia-redis
    image: "redis:alpine"
    pull: yes
    recreate: true
    container_default_behavior: compatibility
    volumes:
      - "{{ authelia.redis.folder }}:/data"
    user: "{{ uid }}:{{ gid }}"
    network_mode: default
    networks:
      - name: authelia
        aliases:
          - "{{ authelia.redis.hostname }}"
    restart_policy: unless-stopped
    state: started
    env:
      TZ: "{{ tz }}"

- name: Create and start authelia container
  docker_container:
    name: authelia
    image: "authelia/authelia:{{ authelia.tag }}"
    pull: yes
    recreate: true
    container_default_behavior: compatibility
    volumes:
      - "{{ authelia.folder }}:/config"
    network_mode: default
    networks:
      - name: web
        aliases:
          - authelia
      - name: postfix
        aliases:
          - authelia
      - name: authelia
        aliases:
          - authelia
    restart_policy: unless-stopped
    state: started
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.authelia.rule: "Host(`{{ authelia.subdomain }}.{{ domain }}`)"
      traefik.http.routers.authelia.entrypoints: "websecure"
      traefik.http.services.authelia.loadbalancer.server.port: "9091"
      # Traefik Authelia Middlewares Config
      traefik.http.middlewares.authelia.forwardauth.address: "http://authelia:9091/api/verify?rd=https://{{ authelia.subdomain }}.{{ domain }}/"
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: "true"
      traefik.http.middlewares.authelia-basic.forwardauth.address: "http://authelia:9091/api/verify?auth=basic"
      traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader: "true"
      # Homer
      homer.enable: "true"
      homer.name: "Authelia"
      homer.service: "Management"
      homer.priority: "100"
      homer.subtitle: "Authentication server providing 2FA and SSO"
      homer.url: "https://{{ authelia.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/png/authelia.png"
      homer.target: "_blank"
    env:
      TZ: "{{ tz }}"