---
- name: Create directories
  file:
    path: "{{ authelia.folder }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Create and start container
  docker_container:
    name: authelia
    image: "authelia/authelia"
    pull: yes
    recreate: true
    volumes:
      - "{{ authelia.folder }}:/config"
    networks:
      - name: web
        aliases:
          - authelia
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.authelia.rule: "Host(`{{ authelia.subdomain }}.{{ domain }}`)"
      traefik.http.routers.authelia.entrypoints: "websecure"
      traefik.http.services.authelia.loadbalancer.server.port: "9091"

      traefik.http.middlewares.authelia.forwardauth.address: "http://authelia:9091/api/verify?rd=https://{{ authelia.subdomain }}.{{ domain }}/"
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: "true"
      traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: "Remote-User, Remote-Groups, Remote-Name, Remote-Email"
      traefik.http.middlewares.authelia-basic.forwardauth.address: "http://authelia:9091/api/verify?auth=basic"
      traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader: "true"
      traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders: "Remote-User, Remote-Groups, Remote-Name, Remote-Email"
    env:
      TZ: "{{ tz }}"