---
- name: Stop and remove any existing container
  docker_container:
    name: nzbget
    state: absent

- name: Create directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ group }} recurse=yes"
  with_items:
    - "{{ nzbget.folder }}"
    - "{{ data_folder }}/data/nzbget"
    - "{{ data_folder }}/data/nzbget/intermediate"

- name: Create and start container
  docker_container:
    name: nzbget
    image: "ghcr.io/linuxserver/nzbget"
    pull: yes
    recreate: true
    volumes:
      - "{{ nzbget.folder }}:/config"
      - "{{ data_folder }}/data/nzbget:/downloads"
      - "{{ data_folder }}/data/nzbget/intermediate:/intermediate"
    networks:
      - name: web
        aliases:
          - nzbget
    restart_policy: unless-stopped
    state: started
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.nzbget.rule: "Host(`{{ nzbget.subdomain }}.{{ domain }}`)"
      traefik.http.routers.nzbget.entrypoints: "websecure"
      traefik.http.services.nzbget.loadbalancer.server.port: "6789"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"