---
- name: Stop and remove any existing container
  community.docker.docker_container:
    name: nzbget
    state: absent

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0775"
    recurse: true
  loop:
    - "{{ nzbget.folder }}"
    - "{{ data_folder }}/usenet/incomplete/nzbget"

- name: Create and start container
  community.docker.docker_container:
    name: nzbget
    image: "ghcr.io/linuxserver/nzbget:{{ nzbget.tag }}"
    pull: true
    recreate: true
    volumes:
      - "{{ nzbget.folder }}:/config"
      - "{{ data_folder }}/data:/data"
    networks:
      - name: web
        aliases:
          - nzbget
    restart_policy: unless-stopped
    state: started
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.nzbget.rule: "Host(`{{ nzbget.subdomain }}.{{ domain }}`)"
      traefik.http.routers.nzbget.entrypoints: "websecure"
      traefik.http.services.nzbget.loadbalancer.server.port: "6789"
      traefik.http.routers.nzbget.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "NZBGet"
      homer.service: "Download"
      homer.priority: "200"
      homer.subtitle: "Efficient Usenet downloader"
      homer.url: "https://{{ nzbget.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/svg/nzbget.svg"
      homer.target: "_blank"
    env:
      TZ: "{{ tz | string }}"
      PUID: "{{ uid | string }}"
      PGID: "{{ gid | string }}"

- name: Settings | Wait for 'nzbget.conf' to be created
  ansible.builtin.wait_for:
    path: "{{ nzbget.folder }}/nzbget.conf"
    state: present

- name: Settings | Wait for 10 seconds before stopping nzbget container
  ansible.builtin.wait_for:
    timeout: 10

- name: Settings | Stop container
  community.docker.docker_container:
    name: nzbget
    state: stopped

- name: Clear leftover folders from first start
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ data_folder }}/usenet/nzb"
    - "{{ data_folder }}/usenet/queue"
    - "{{ data_folder }}/usenet/tmp"
    - "{{ data_folder }}/usenet/nzbget.log"

- name: NZBGet Main Settings Tasks
  ansible.builtin.include_tasks: "settings/main.yml"
- name: NZBGet Directories Settings Tasks
  ansible.builtin.include_tasks: "settings/directories.yml"
- name: NZBGet Categories Settings Tasks
  ansible.builtin.include_tasks: "settings/categories.yml"
- name: Re-Start NZBGet container
  community.docker.docker_container:
    name: nzbget
    state: started
