---
- name: Create directories
  file:
    path: "{{ sonarr.folder }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775

- name: Create and start container
  docker_container:
    name: sonarr
    image: "ghcr.io/linuxserver/sonarr"
    pull: yes
    recreate: true
    volumes:
      - "{{ sonarr.folder }}:/config"
      - "{{ data_folder }}:/data"
    networks:
      - name: web
        aliases:
          - sonarr
    restart_policy: unless-stopped
    state: started
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.sonarr.rule: "Host(`{{ sonarr.subdomain }}.{{ domain }}`)"
      traefik.http.routers.sonarr.entrypoints: "websecure"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
      traefik.http.routers.sonarr.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "Sonarr"
      homer.service: "PVR"
      homer.priority: "400"
      homer.subtitle: "PVR for Usenet and BitTorrent users"
      homer.url: "https://{{ sonarr.subdomain }}.{{ domain }}"
      homer.logo: "assets/homer-icons/svg/sonarr.svg"
      homer.target: "_blank"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"

- name: Wait for 'config.xml' to be created
  wait_for:
    path: "{{ sonarr.folder }}/config.xml"
    state: present

- name: Wait for 10 seconds
  wait_for:
    timeout: 10

- name: Settings Tasks
  include_tasks: "settings/main.yml"