- name: Settings | Wait for 'rtorrent.rc' to be created
  wait_for:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    state: present

- name: Settings | Wait for 'php-local.ini' to be created
  wait_for:
    path: "{{ rutorrent.folder }}/php/php-local.ini"
    state: present

- name: Settings | Wait for 'nginx.conf' to be created
  wait_for:
    path: "{{ rutorrent.folder }}/nginx/nginx.conf"
    state: present

- name: Settings | Wait for 'plugins.ini' to be created
  wait_for:
    path: "{{ rutorrent.folder }}/rutorrent/settings/plugins.ini"
    state: present

- name: Settings | Wait for 10 seconds before stopping rutorrent container
  wait_for:
    timeout: 10

- name: Settings | Stop container
  docker_container:
    name: rutorrent
    state: stopped

## ruTorrent Static Settings Tasks

- name: Settings | ruTorrent Static Settings Tasks
  include_tasks: "static.yml"
  when: (not rtorrent_rc.stat.exists)

## ruTorrent Dynamic Settings Tasks

- name: Settings | ruTorrent Dynamic Settings Tasks
  include_tasks: "dynamic.yml"

- name: Settings | Start container
  docker_container:
    name: rutorrent
    state: started