---
## rtorrent.rc

# Disable DHT - i.e. disables trackerless torrents.
- name: Settings | Static | Disable DHT
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^dht\.mode\.set\s*=.*'
    line: 'dht.mode.set = disable'
    state: present

# Disable Peer exchange (PEX) - i.e. allows torrents marked private, only.
- name: Settings | Static | Disable PEX
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^protocol\.pex\.set\s*=.*'
    line: 'protocol.pex.set = no'
    state: present

# Minimum number of peers to connect to per torrent
- name: Settings | Static | Reduce 'min_peers'
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^throttle\.min_peers\.normal\.set\s*=.*'
    line: 'throttle.min_peers.normal.set = 1'
    state: present

# Maximum number of simultaneous upload slots per torrent.
- name: Settings | Static | Increase 'max_uploads'
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^throttle\.max_uploads\.set\s*=.*'
    line: 'throttle.max_uploads.set = 1024'
    state: present

# Maximum number of simultaneous downloads slots globally
- name: Settings | Static | Set 'max_downloads_global' to 1024
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^throttle\.max_downloads\.global\.set\s*=.*'
    line: 'throttle.max_downloads.global.set = 1024'
    state: present

# Maximum number of simultaneous downloads and uploads slots globally
- name: Settings | Static | Set 'max_uploads_global' to 1024
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^throttle\.max_uploads\.global\.set\s*=.*'
    line: 'throttle.max_uploads.global.set = 1024'
    state: present

# Global download rate in KiB
- name: Settings | Static | Set 'global_download_rate' to unlimited
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^throttle\.global_down\.max_rate\.set_kb\s*=.*'
    line: 'throttle.global_down.max_rate.set_kb = 0'
    state: present

# Global upload rate in KiB
- name: Settings | Static | Set 'global_upload_rate' to unlimited
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^throttle\.global_up\.max_rate\.set_kb\s*=.*'
    line: 'throttle.global_up.max_rate.set_kb = 0'
    state: present

# Maximum number of open files rtorrent can keep open.
- name: Settings | Static | Set 'max_open_files' to 1024
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^network\.max_open_files\.set\s*=.*'
    line: 'network.max_open_files.set = 1024'
    state: present

- name: Settings | Static | Set encryption parameters
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^protocol\.encryption\.set\s*=.*'
    line: 'protocol.encryption.set = allow_incoming,try_outgoing,enable_retry,prefer_plaintext'
    state: present

- name: Settings | Static | Disable - Hash check
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^pieces\.hash\.on_completion\.set\s*=.*'
    line: 'pieces.hash.on_completion.set = no'
    state: present

# Allocate disk space
- name: Settings | Static | Disable 'file_allocate'
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^system\.file\.allocate\.set\s*=.*'
    line: 'system.file.allocate.set = 0'
    state: present

- name: Settings | Static | Set download directory
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^directory\.default\.set\s*=.*'
    line: 'directory.default.set = /downloads/completed'
    state: present

- name: Settings | Static | Set watched directory
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^.*#.*schedule.*=.*watch_directory.*'
    line: 'schedule = watch_directory,5,5,"load.start=/downloads/watched/*.torrent,d.delete_tied="'
    state: present

- name: Settings | Static | Set 'network.xmlrpc.size_limit.set' to 20M
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    regexp: '^network\.xmlrpc\.size_limit\.set\s*=.*'
    line: 'network.xmlrpc.size_limit.set = 20M'
    state: present

- name: Settings | Static | Add line space
  lineinfile:
    path: "{{ rutorrent.folder }}/rtorrent/rtorrent.rc"
    insertbefore: 'network.xmlrpc.size_limit.set = 20M'
    line: ""
    state: present

## php-local.ini
- name: Settings | Static | Set 'upload_max_filesize' to 20M
  lineinfile:
    path: "{{ rutorrent.folder }}/php/php-local.ini"
    regexp: '^upload_max_filesize\s*=.*'
    line: 'upload_max_filesize = 20M'
    state: present

## plugins.ini
- name: Settings | Static | Import custom 'plugins.ini'
  copy:
    src: plugins.ini
    dest: "{{ rutorrent.folder }}/rutorrent/settings/plugins.ini"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
    force: yes