---
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg

- name: Remove the legacy Docker repository list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present
    enabled: true

- name: Install Docker required packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    install_recommends: true
    update_cache: true
  notify:
    - Start Docker

- name: Add the default user to the docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true
  notify:
    - Notify that the docker group needs a fresh session
