---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0775"
    recurse: true
  loop:
    - "{{ traefik.folder }}"
    - "{{ traefik.folder }}/certificates"
    - "{{ traefik.folder }}/logs"

- name: Download Cloudflare certificate for mTLS
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { url: "https://developers.cloudflare.com/ssl/static/authenticated_origin_pull_ca.pem",
        dest: "{{ traefik.folder }}/certificates/cf_authenticated_origin_pull_ca.pem" }

- name: Creating origin_certificate.pem
  ansible.builtin.copy:
    dest: "{{ traefik.folder }}/certificates/origin_certificate.pem"
    content: "{{ traefik.origin_certificate }}"
    mode: "0644"

- name: Creating origin_certificate.key
  ansible.builtin.copy:
    dest: "{{ traefik.folder }}/certificates/origin_certificate.key"
    content: "{{ traefik.origin_certificate_private_key }}"
    mode: "0644"

- name: Adding traefik.yml file
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ traefik.folder }}/traefik.yml"
    mode: "0600"

- name: Adding dynamic.yml file
  ansible.builtin.template:
    src: dynamic.yml.j2
    dest: "{{ traefik.folder }}/dynamic.yml"
    mode: "0600"

- name: Ensure access.log file exists
  ansible.builtin.file:
    path: "{{ traefik.folder }}/logs/access.log"
    state: touch
    mode: "0600"

- name: Create the web network
  community.docker.docker_network:
    name: web

- name: Create the traefik container
  community.docker.docker_container:
    name: traefik
    image: "traefik:{{ traefik.tag }}"
    restart_policy: always
    recreate: true
    networks:
      - name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ traefik.folder }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik.folder }}/dynamic.yml:/etc/traefik/dynamic/dynamic.yml"
      - "{{ traefik.folder }}/certificates/cf_authenticated_origin_pull_ca.pem:/etc/traefik/dynamic/authenticated_origin_pull_ca.pem:ro"
      - "{{ traefik.folder }}/certificates/origin_certificate.pem:/etc/traefik/dynamic/{{ domain }}.pem:ro"
      - "{{ traefik.folder }}/certificates/origin_certificate.key:/etc/traefik/dynamic/{{ domain }}.key:ro"
      - "{{ traefik.folder }}/logs/access.log:/var/log/traefik/access.log"
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik.api_url }}`)"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "Traefik"
      homer.service: "Management"
      homer.priority: "400"
      homer.subtitle: "Dashboard of the Traefik proxy"
      homer.url: "https://{{ traefik.api_url }}"
      homer.logo: "assets/homer-icons/svg/traefik-proxy.svg"
      homer.target: "_blank"
    env:
      CF_API_KEY: "{{ cloudflare.api_key }}"
      CF_API_EMAIL: "{{ cloudflare.api_email }}"

- name: Enroll Traefik Firewall Bouncer
  community.docker.docker_container_exec:
    container: crowdsec
    command: "cscli bouncers add traefik-bouncer --key {{ crowdsec.traefik_bouncer_key }}"
  register: crowdsec_bouncer_add
  failed_when: >
    crowdsec_bouncer_add.rc != 0 and 'already exists' not in (crowdsec_bouncer_add.stderr | default(''))
  when: use_crowdsec | bool
