---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
    recurse: yes
  loop:
    - "{{ traefik.folder }}"
    - "{{ traefik.folder }}/certificates"

- name: Download Cloudflare certificate for mTLS
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { url: "https://developers.cloudflare.com/ssl/static/authenticated_origin_pull_ca.pem", dest: "{{ traefik.folder }}/certificates/cf_authenticated_origin_pull_ca.pem" }

- name: Creating origin_certificate.pem
  copy:
    dest: "{{ traefik.folder }}/certificates/origin_certificate.pem"
    content: "{{ traefik.origin_certificate }}"

- name: Creating origin_certificate.key
  copy:
    dest: "{{ traefik.folder }}/certificates/origin_certificate.key"
    content: "{{ traefik.origin_certificate_private_key }}"

- name: Adding traefik.yml file
  template:
    src: traefik.yml.j2
    dest: "{{ traefik.folder }}/traefik.yml"
    mode: 0600

- name: Adding dynamic.yml file
  template:
    src: dynamic.yml.j2
    dest: "{{ traefik.folder }}/dynamic.yml"
    mode: 0600

- name: Create the web network
  docker_network:
    name: web

- name: Create the traefik container
  docker_container:
    name: traefik
    image: "traefik:{{ traefik.tag }}"
    restart_policy: always
    recreate: true
    networks:
      - name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ traefik.folder }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik.folder }}/dynamic.yml:/etc/traefik/dynamic/dynamic.yml"
      - "{{ traefik.folder }}/certificates/cf_authenticated_origin_pull_ca.pem:/etc/traefik/dynamic/authenticated_origin_pull_ca.pem"
      - "{{ traefik.folder }}/certificates/origin_certificate.pem:/etc/traefik/dynamic/{{ domain }}.pem"
      - "{{ traefik.folder }}/certificates/origin_certificate.key:/etc/traefik/dynamic/{{ domain }}.key"
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # Traefik
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik.api_url }}`)"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: "authelia@docker"
      # Homer
      homer.enable: "true"
      homer.name: "Traefik"
      homer.service: "Management"
      homer.priority: "400"
      homer.subtitle: "Dashboard of the Traefik proxy"
      homer.url: "https://{{ traefik.api_url }}"
      homer.logo: "assets/homer-icons/png/traefik.png"
      homer.target: "_blank"
    env:
      CF_API_KEY: "{{ cloudflare.api_key }}"
      CF_API_EMAIL: "{{ cloudflare.api_email }}"
