- name: Install syslog-ng
  become: true
  ansible.builtin.apt:
    name: syslog-ng
    state: present
    update_cache: true

- name: Download CrowdSec installer script
  become: true
  ansible.builtin.get_url:
    url: https://install.crowdsec.net
    dest: /tmp/install-crowdsec.sh
    mode: "0755"
    force: true

- name: Install CrowdSec Repository
  become: true
  ansible.builtin.command: /tmp/install-crowdsec.sh

- name: Install CrowdSec firewall bouncer
  become: true
  ansible.builtin.apt:
    name: crowdsec-firewall-bouncer-iptables
    state: present
    update_cache: true

- name: Create firewall bouncer config file
  ansible.builtin.template:
    src: firewall-bouncer.yaml.j2
    dest: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
    force: true
    owner: root
    group: root
    mode: "0600"

- name: Enable and start CrowdSec Firewall Bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    enabled: true
    state: started
