---
- name: Install logwatch packages
  ansible.builtin.package:
    name:
      - sendmail
      - logwatch
    state: present
    install_recommends: true

- name: Check that logwatch.conf exists
  ansible.builtin.stat:
    path: /etc/logwatch/conf/logwatch.conf
  register: logwatch_state

- name: Create Logwatch configuration
  ansible.builtin.copy:
    src: /usr/share/logwatch/default.conf/logwatch.conf
    dest: /etc/logwatch/conf/logwatch.conf
    remote_src: true
    mode: "0644"
  when: not logwatch_state.stat.exists

- name: Ensure Format is html
  ansible.builtin.lineinfile:
    path: /etc/logwatch/conf/logwatch.conf
    regexp: "^Format ="
    line: Format = html

- name: Ensure MailTo is set
  ansible.builtin.lineinfile:
    path: /etc/logwatch/conf/logwatch.conf
    regexp: "^MailTo ="
    line: MailTo = {{ notifications_email }}

- name: Ensure Detail is Med
  ansible.builtin.lineinfile:
    path: /etc/logwatch/conf/logwatch.conf
    regexp: "^Detail ="
    line: Detail = Med

- name: Ensure temporary folder for logwatch exist
  ansible.builtin.file:
    path: /var/cache/logwatch
    state: directory
    mode: "0755"
