---
- name: Cloudflare | Dynamic DNS Updater
  ansible.builtin.include_tasks: "ddns/main.yml"
  when: dynamic_ip | bool

- name: Cloudflare | Traefik Companion
  ansible.builtin.include_tasks: "traefik/main.yml"
